[project]
name = "gita"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "keyring>=25.7.0",
    "rich>=14.3.2",
    "typer>=0.23.1",
]

[project.scripts]
gita = "gita.main:app"